SET NAMES utf8mb4;

-- CLIENTES (con login)
CREATE TABLE IF NOT EXISTS clientes (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(80) NOT NULL,
  apellido VARCHAR(100) NOT NULL,
  domicilio VARCHAR(150) NOT NULL,
  credito FLOAT DEFAULT 0,
  email VARCHAR(120) NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  creado_en DATETIME DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uq_clientes_email (emailÍndice)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- PRODUCTO
CREATE TABLE IF NOT EXISTS producto (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(50) NOT NULL,
  descripcion VARCHAR(200),
  precio DECIMAL(10,2) NOT NULL,
  existencias INT NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- VENTAS
CREATE TABLE IF NOT EXISTS ventas (
  ventaID INT AUTO_INCREMENT PRIMARY KEY,
  clienteID INT NOT NULL,
  fechaVenta DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  total DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  CONSTRAINT fk_ventas_cliente
    FOREIGN KEY (clienteID) REFERENCES clientes(id)
    ON UPDATE CASCADE
    ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- DETALLES
CREATE TABLE IF NOT EXISTS detallesventa (
  detalleID INT AUTO_INCREMENT PRIMARY KEY,
  ventaID INT NOT NULL,
  productoID INT NOT NULL,
  cantidad INT NOT NULL,
  preciounitario DECIMAL(10,2) NOT NULL,
  subtotal DECIMAL(10,2) NOT NULL,
  CONSTRAINT fk_detalles_venta
    FOREIGN KEY (ventaID) REFERENCES ventas(ventaID)
    ON UPDATE CASCADE
    ON DELETE CASCADE,
  CONSTRAINT fk_detalles_producto
    FOREIGN KEY (productoID) REFERENCES producto(id)
    ON UPDATE CASCADE
    ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
